---
title: "Untitled"
output: html_document
date: '2023-04-01'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
### N=2，df=1，SS=230
chisq_dist <- rchisq(n =  10e3, df =  1)
plot(density(chisq_dist), main = "Chi-Squared Density Plot(df=1)", xlab = "Value", ylab = "Density")# $chi^2$ density plot
qchisq(c(.025,.975),df = 1)# $c_L,c_R$
abline(v = qchisq(c(.025,.975),df = 1),lty=2)
sigma_cl <- sqrt((SS <- 230)/qchisq(c(.975),df = 1))
sigma_cr <- sqrt(SS/qchisq(c(.025),df = 1))
cat("sigma 95%CI:[",sigma_cl, sigma_cr,"]", "\n")

### N=100，df=99，SS=2285
chisq_dist <- rchisq(n =  10e3, df =  99)
plot(density(chisq_dist), main = "Chi-Squared Density Plot(df=99)", xlab = "Value", ylab = "Density")# $chi^2$ density plot
qchisq(c(.025,.975),df = 99)#$c_L,c_R$
abline(v = qchisq(c(.025,.975),df = 99),lty=2)
sigma_cl <- sqrt((SS <- 2285)/qchisq(c(.975),df = 99))
sigma_cr <- sqrt(SS/qchisq(c(.025),df = 99))
cat("sigma 95%CI:[",sigma_cl, sigma_cr,"]", "\n")

```


